--- 
title: "2021 UQ Spatial Planning Workshop using Prioritizr"
author: "Jason D. Everett, Isaac Brito-Morales"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: references.bib
csl: reference-style.csl
biblio-style: apalike
link-citations: yes
description: "Notes for the 2021 UQ Spatial Planning Workshop using Prioritizr."
url: "https://mathmarecol.github.io/SpatialPlanning_Workshop2021/"
github-repo: MathMarEcol/SpatialPlanning_Workshop2021
fontsize: 12pt
urlcolor: blue
geometry: "left=2.54cm, right=2.54cm, top=2.54cm, bottom=2.54cm"
---

# Welcome!

The aim of this workshop is to help you get started with using the prioritizr R package for systematic conservation planning. It is not designed to give you a comprehensive overview and you will not become an expert after completing this workshop. Instead, we want to help you understand the core principles of conservation planning and guide you through some of the common tasks involved with developing prioritizations. In other words, we want to give you the knowledge base and confidence needed to start applying systematic conservation planning to your own work.

The workshop will run 6-9 am (Brisbane Time) on Tuesday 9th and Wednesday 10th February 20201 to accommodate our European friends. The rough plan for the workshop is to cover Chapters 1-3 on Day 1, and Chapters 4-5 on Day 2. We hope this will leave lots of time for discussion.
